filebeat.inputs: 
- type: log
  paths:
    - /root/code/go-garden/examples/gateway/runtime/*.log
    - /root/code/go-garden/examples/pay/runtime/*.log
    - /root/code/go-garden/examples/user/runtime/*.log
    - /root/code/go-garden/examples/user2/runtime/*.log

setup.template.enabled: false
setup.ilm.enabled: false

processors:
 - decode_json_fields:
     fields: ['level', 'time', 'caller', 'message']
     target: ''
     overwrite_keys: true
 - timestamp:
     field: time
     timezone: Asia/Shanghai
     layouts:
       - '2006-01-02 15:04:05'
       - '2006-01-02 15:04:05.999'
     test:
       - '2019-06-22 16:33:51'
 - drop_fields:
     fields: ['message', 'input', 'agent', 'ecs', 'log']

output.elasticsearch:
   hosts: ["192.168.129.154:9200"]
   allow_older_versions: true
   index: logs